openapi: 3.0.0
info:
  title: Jobs API
  description: An API to manage job scheduling and execution details.
  version: "1.0.0"
servers:
  - url: https://service.api.openbridge.io

paths:
  /service/jobs/jobs:
    get:
      summary: List all jobs
      operationId: listJobs
      parameters:
        - name: subscription_ids
          in: query
          required: true
          description: Subscription ID.
          schema:
            type: integer
        - name: page
          in: query
          required: true
          description: The page number of the pagination.
          schema:
            type: integer
        - name: page_size
          in: query
          required: true
          description: The page number of the pagination.
          schema:
            type: integer
            default: 10

      responses:
        '200':
          description: A list of jobs
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    $ref: '#/components/schemas/Links'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
                  meta:
                    $ref: '#/components/schemas/Meta'
components:
  schemas:
    Links:
      type: object
      properties:
        first:
          type: string
          format: uri
        last:
          type: string
          format: uri
        prev:
          type: string
          format: uri
          nullable: true
        next:
          type: string
          format: uri
          nullable: true
    Job:
      type: object
      required:
        - type
        - id
        - attributes
      properties:
        type:
          type: string
        id:
          type: string
        attributes:
          $ref: '#/components/schemas/JobAttributes'
    JobAttributes:
      type: object
      properties:
        report_date:
          type: string
          format: date-time
          nullable: true
        subscription_id:
          type: integer
        valid_date_start:
          type: string
          format: date
        valid_date_end:
          type: string
          format: date
        status:
          type: string
        schedule:
          type: string
        orig_schedule:
          type: string
        request_start:
          type: integer
        request_end:
          type: integer
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
        is_primary:
          type: boolean
        stage_id:
          type: integer
        extra_context:
          type: string
          nullable: true
        product_id:
          type: integer
        subproduct_id:
          type: string
    Meta:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
    Pagination:
      type: object
      properties:
        page:
          type: integer
        pages:
          type: integer
        count:
          type: integer
