openapi: 3.0.0
info:
  title: Service API
  description: An API to talk to many 3rd party APUs.
  version: "1.0.0"
servers:
  - url: https://service.api.openbridge.io

paths:
  /service/rules/prod/v1/rules/search:
    get:
      summary: Retrieve the schema of a given product table using a path key.
      operationId: getData
      parameters:
        - name: path
          in: query
          required: true
          description: Search path to find schema
          schema:
            type: string
        - name: latest
          in: query
          required: true
          description: If "true" return the most recent version.
          schema:
            type: string
            default: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DataItem'
                  links:
                    type: object
components:
  schemas:
    Links:
      type: object
      properties:
        first:
          type: string
          format: uri
        last:
          type: string
          format: uri
        prev:
          type: string
          format: uri
          nullable: true
        next:
          type: string
          format: uri
          nullable: true
    Meta:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
    Pagination:
      type: object
      properties:
        page:
          type: integer
        pages:
          type: integer
        count:
          type: integer
    DataItem:
      type: object
      properties:
        attributes:
          type: object
          properties:
            account_id:
              type: string
            path:
              type: string
            rules:
              type: object
              properties:
                configuration:
                  type: object
                  properties:
                    load:
                      type: object
                      properties:
                        prepend_headers:
                          type: boolean
                        schema:
                          type: object
                          properties:
                            fields:
                              type: array
                              items:
                                $ref: '#/components/schemas/Field'
                destination:
                  type: object
                  properties:
                    tablename:
                      type: string
                dialect:
                  type: object
                  properties:
                    delimiter:
                      type: string
                    doublequote:
                      type: boolean
                    encoding:
                      type: string
                    lineterminator:
                      type: string
                    quotechar:
                      type: string
                    quoting:
                      type: integer
                    skipinitialspace:
                      type: boolean
                meta:
                  type: object
                  properties:
                    creation_date:
                      type: string
                    version:
                      type: integer
        version:
          type: integer
    Field:
      type: object
      properties:
        default:
          type: string
        include_in_checksum:
          type: boolean
        name:
          type: string
        type:
          type: string